run:
  timeout: 5m
  skip-dirs:
    - vendor
linters:
  fast: false
  enable-all: false
  disable-all: false
  presets:
    - performance
    - format
    - complexity
    - bugs
    - unused
  disable:
    - musttag
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/informalict/ports)
